<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />

    <xacro:property name="link2_length" value="0.1" />
    <xacro:property name="link2_width" value="0.1" />
    <xacro:property name="link2_height" value="1.0" />

    <xacro:property name="link3_length" value="0.1" />
    <xacro:property name="link3_width" value="0.1" />
    <xacro:property name="link3_height" value="1.0" />

    <link name="base_link">
        <static>true</static>
        <inertial>
            <mass value="1" />

            <inertia ixx="1" ixy="0" ixz="0"
                iyy="1" iyz="0"
                izz="1" />
        </inertial>
    </link>

    <link name="link_1">
        <inertial>
            <mass value="1" />

            <inertia ixx="1" ixy="0" ixz="0"
                iyy="1" iyz="0"
                izz="1" />
        </inertial>
    </link>

    <link name="link_2">
        <visual>
            <geometry>
                <box size="${link2_length} ${link2_width} ${link2_height}" />
            </geometry>
            <origin xyz="0 0 ${link2_height / 2.0}" rpy="0 0 0" />
        </visual>
        <xacro:box_inertia m="0.1" w="${link2_width}" h="${link2_height}" d="${link2_length}"
            xyz="0 0 ${link2_height / 2.0}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${link2_length} ${link2_width} ${link2_height}" />
            </geometry>
            <origin xyz="0 0 ${link2_height / 2.0}" rpy="0 0 0" />
        </collision>
    </link>

    <link name="link_3">
        <visual>
            <geometry>
                <box size="${link3_length} ${link3_width} ${link3_height}" />
            </geometry>
            <origin xyz="0 0 ${link3_height / 2.0}" rpy="0 0 0" />
        </visual>
        <xacro:box_inertia m="0.1" w="${link3_width}" h="${link3_height}" d="${link3_length}"
            xyz="0 0 ${link3_height / 2.0}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${link3_length} ${link3_width} ${link3_height}" />
            </geometry>
            <origin xyz="0 0 ${link3_height / 2.0}" rpy="0 0 0" />
        </collision>
    </link>

    <joint name="base_to_link1" type="continuous">
        <parent link="base_link" />
        <child link="link_1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="link1_to_link2" type="continuous">
        <parent link="link_1" />
        <child link="link_2" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="link2_to_link3" type="continuous">
        <parent link="link_2" />
        <child link="link_3" />
        <origin xyz="0 0 ${link2_height}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>


    <!-- <xacro:include filename="transmission.xacro" /> -->
    <xacro:include filename="gazebo.xacro" />

</robot>